databases:
  - name: hurryUp-bd
    databaseName: hurryup_bd_qs0l
    user: hurryup_bd_user
    ipAllowList: []

services:
  - type: web
    name: back-hurryup
    env: ruby
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hurryUp-bd
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false