development:
  secret_key_base: 'secret'
  #allowed_origins:
  #  - https://hurryup-diagnosticos.vercel.app/
  #  - http://localhost:3000

test:
  secret_key_base: 'secret_test'
production:
  secret_key_base: 'secret_prod' 
  #allowed_origins:
  #  - https://hurryup-diagnosticos.vercel.app/
  #  - http://localhost:3000
#<%= ENV["SECRET_KEY_BASE"] %>
